config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tenders
  get 'pages/home'

  get 'pages/academics'

  get 'pages/ug'

  get 'pages/pg'

  get 'pages/vocational'

  get 'pages/contact'
  
  root 'pages#home'

  get "*path" => redirect('/')

  

end

app/models/tender.rb
class Tender < ActiveRecord::Base
if Rails.env.devlopmet?
has_attached_file :document

else	
has_attached_file :document,
				:storage => :dropbox,
    			:dropbox_credentials => Rails.root.join("config/dropbox.yml")

validates_attachment :document, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}

   end				      
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def academics
  end

  def ug
  end

  def pg
  end

  def vocational
  end

  def contact
  end
end

app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  before_action :set_tender, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tenders
  # GET /tenders.json
  def index
    @tenders = Tender.all
  end

  # GET /tenders/1
  # GET /tenders/1.json
  def show
  end

  # GET /tenders/new
  def new
    @tender = Tender.new
  end

  # GET /tenders/1/edit
  def edit
  end

  # POST /tenders
  # POST /tenders.json
  def create
    @tender = Tender.new(tender_params)

    respond_to do |format|
      if @tender.save
        format.html { redirect_to @tender, notice: 'Tender was successfully created.' }
        format.json { render :show, status: :created, location: @tender }
      else
        format.html { render :new }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenders/1
  # PATCH/PUT /tenders/1.json
  def update
    respond_to do |format|
      if @tender.update(tender_params)
        format.html { redirect_to @tender, notice: 'Tender was successfully updated.' }
        format.json { render :show, status: :ok, location: @tender }
      else
        format.html { render :edit }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenders/1
  # DELETE /tenders/1.json
  def destroy
    @tender.destroy
    respond_to do |format|
      format.html { redirect_to tenders_url, notice: 'Tender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tender
      @tender = Tender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tender_params
      params.require(:tender).permit(:tender_details, :tender_publish_date, :tender_due_date, :document)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Jawahar Lal Nehru College</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav">
        
        <li><%= link_to "Home", pages_home_path %></li> <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Academics", pages_academics_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>

        <% if user_signed_in? %>

        
        <li><%= link_to "Sign_Out", destroy_user_session_path, method: :delete %></li> 
        <% else %>   
        <li><%= link_to "Sign_In", new_user_session_path %></li>
        <% end %>


        </ul>
       </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jlnc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
	
<%= render 'layouts/header' %>


<%= yield %>



</body>

<script>
$(document).ready(function(){
 $('.owl-carousel').owlCarousel({
    autoPlay: false,
    items: 4
 });
});
</script>
</html>

app/views/pages/academics.html.erb
<div class="page" >
  <div class="container">
    <div class="row">
  <div class="lines">
<div class="breadcrum-wrap"><h5>Vision, Mission & Objective</div></h5>
<p>
<p>Jawahar Lal Nehru College is committed to the pursuit of excellence in higher education, character building and total development of personality and responsible citizenship.</p>
<p>Strategies to achieve these goals:</p>
<p><strong>Pursuit of Excellence: </p></strong>
<p>> Optimum transparency in admission of students 
     and faculty appointments, upholding merit as    
     the foremost criterion.</p>
<p>> Maintenance of a robust work culture.</p>
<p>> Discipline combined with freedom of thought   
      and expression.</p>
<p>> A sense of national consciousness. </p>

<p><strong>Character Building: </p></strong>
<p>It is woven into the total learning environment. Students are encouraged to be honest and hardworking, courteous in behaviour towards all, faculty members to be caring and responsive, and emphasis is laid on personal dignity as well as simplicity and austerity in the total life of the college. </p>

<p><strong>Total Development of Personality: </p></strong>
<p>Class-room teaching is complemented with co-curricular activities, where students work under the supervision of teachers.</p>
<p><strong>Discipline:</p></strong>
<p>The  understands ‘discipline’ as the ability to uphold universal values in day-to-day work and conduct. Discipline is balanced with freedom, lest it gets equated with mere conformity, which is undermines personality development.</p>
<hr>
<p>The <strong>mission</strong> of Jawahar Lal Nehru College is to educate young men and women within a framework of liberal and republican values, to equip them to excel in the service of the nation and to attain optimum personal fulfillment by leading a values-based life.</p><hr>
<p><strong>Communication</strong></p>
<p>The vision and goals stated above are communicated to the entire student body in two broad ways:
<p>
> By transferring the vision to the teaching fraternity through frequent interactions that are informal in nature.</p>
<p>
> A more formal strategy is used in respect of the students. Through morning assembles, attended by all first year students, the Principal addresses the students and educates them in these respects. </p>
<p>The college has a large number of scholarships to promote the pursuit of excellence. Innumerable scholarly activities – including seminars, conferences and workshops are organized to rein force this. In all of these, students and teachers work closely together. Tutorials and lectures are conducted with utmost regularity. 
Teacher truancy is virtually absent in J.L.N College this total ambience distinguished by an earnest and dedicated attitude to work as well as to the welfare of students is the most powerful communication there can be.</p>

    <hr>
    <hr>

app/views/pages/contact.html.erb
<div class="container">
	<div class="row">
<h1>Contact</h1>
<h2>Jawahar Lal Nehru College</h2>
<p>Rajabari Road</p>
<p>Chakradharpur-833102</p>
<p>West Singhbhum</p>
<p>Jharkhand</p>
<br>
<p>Phone/Fax : 06587-238139</p>
<p>jlncollegeorg.ckp@gmail.com<p>
</div>
</div>

app/views/pages/page2.html.erb
<div class="page" >
  <div class="container">
    <div class="row">
  <div class="lines">
<div class="breadcrum-wrap"><h5>Under Graduate Programs</div></h5>
<p>

app/views/pages/pg.html.erb
<div class="page" >
  <div class="container">
    <div class="row">
  <div class="lines">
<div class="breadcrum-wrap"><h5>Under Graduate Programs</div></h5>
<p>
	<p>

<strong>1. Bachelor of Arts (Honours) </Strong>
<p>
<strong>The Page is UNDER CONSTRUCTION</strong></p>

app/views/pages/ug.html.erb
<div class="page" >
  <div class="container">
    <div class="row">
  <div class="lines">
<div class="breadcrum-wrap"><h5>Under Graduate Programs</div></h5>
<p>
	<p>

<strong>1. Bachelor of Arts (Honours) </Strong>
<p>
<strong>	Course Structure</strong></p>
<table cellspacing='0'> <!-- cellspacing='0' is important, must stay -->

	<!-- Table Header -->
	<thead>
		<tr>
			<th>Degree Courses</th>
			<th>Honours</th>
			<th>Subsidiary</th>
			<th>Compulsory Language</th>
			<th>Total</th>
		</tr>
	</thead>
	<!-- Table Header -->

	<!-- Table Body -->
	<tbody>

		<tr>
			<td>Part I</td>
			<td>2 Papers</td>
			<td>2 Papers</td>
			<td>1 Paper</td>
			<td>5 Papers</td>
		</tr><!-- Table Row -->

		<tr class="even">
			<td>Part 2</td>
			<td>2 Papers</td>
			<td>2 Papers</td>
			<td>1 Paper</td>
			<td>5 Papers</td>
		</tr><!-- Darker Table Row -->

		<tr>
			<td>Part 3</td>
			<td>4 Papers</td>
			<td>- - -</td>
			<td>1 Paper</td>
			<td>5 Papers</td>
		</tr>

		

	</tbody>
	<!-- Table Body -->

</table>
<p>

<strong>Honours Paper </strong>:Candidates shall choose any one from below :-
</p>
<p>Hindi, English, Bangla, Urdu, Oriya, Sanskrit, History, Political Science, Philosophy, Economics,
Psychology, Home Science, Geography.</p>
<p>

<strong>Subsidiary Paper </strong>:Two subject from the above list(except the one as an Honours subject) may be chosen as Subsidiary subjects.
</p>
<p>

<strong>Compulsory Paper </strong>: Composition
</p>
<p> a. For Hindi students : Hindi 100 marks  </p>
<p> b. For Non-Hindi students : 50 Marks Hindi & 50 marks Mil (Bangla/Urdu/Oriya/Alt.Eng/Santhali/Ho)</p>
<hr>
<p>
	<strong>2. Bachelor of Commerce (Honours) </Strong>
<p>
<strong>	Course Structure</strong></p>
<table cellspacing='0'> <!-- cellspacing='0' is important, must stay -->

	<!-- Table Header -->
	<thead>
		<tr>
			<th>Degree Courses</th>
			<th>Honours</th>
			<th>Subsidiary</th>
			<th>Compulsory Language</th>
			<th>Total</th>
		</tr>
	</thead>
	<!-- Table Header -->

	<!-- Table Body -->
	<tbody>

		<tr>
			<td>Part I</td>
			<td>2 Papers </td>
			<td>2 Papers</td>
			<td>1 Paper</td>
			<td>5 Papers</td>
		</tr><!-- Table Row -->

		<tr class="even">
			<td>Part 2</td>
			<td>2 Papers</td>
			<td>2 Papers</td>
			<td>1 Paper</td>
			<td>5 Papers</td>
		</tr><!-- Darker Table Row -->

		<tr>
			<td>Part 3</td>
			<td>4 Papers</td>
			<td>- - -</td>
			<td>1 Paper</td>
			<td>5 Papers</td>
		</tr>

		

	</tbody>
	<!-- Table Body -->

</table>



<p><b>Part I </p>
<div class="container">
<div class="col-md-3">
<p><strong>Honours Paper</strong></b></p><p>Financial Accounting</p>
<p>Auditing</p>


</div>

<div class="col-md-3">
<p><strong>Subsidiary Paper</strong></b></p><p>Principles of Economics</p>
<p>Business Organisation</p>

</div>
</div>

<p><b>Part II </p>
<div class="container">
<div class="col-md-3">
<p><strong>Honours Paper</strong></b></p><p>Business Laws</p>
<p>Specialized Accounts</p>


</div>

<div class="col-md-3">
<p><strong>Subsidiary Paper</strong></b></p><p>Money & Banking</p>
<p>Planning & Economic Development</p>

</div>
</div>

<p><b>Part III </p>
<div class="container">
<div class="col-md-3">
<p><strong>Honours Paper</strong></b></p>
<p>Cost Accountancy</p>
<p>Management Accounting</p>
<p>Taxation Laws & Accounts</p>
<p>Business Statistics & Elementary Maths</p>



</div>
</div>
<p>

<strong>Compulsory Paper </strong>: Composition
</p>
<p> a. For Hindi students : Hindi 100 marks  </p>
<p> b. For Non-Hindi students : 50 Marks Hindi & 50 marks Mil (Bangla/Urdu/Oriya/Alt.Eng/Santhali/Ho)</p>
<hr>

<p>
	<strong>3. Bachelor of Science (Honours) </Strong>
</p>

<p>

<strong>Honours Paper </strong>:Candidates shall choose any one from below :-
</p>
<p>Physics</p>
<p>Chemistry</p>
<p>Mathemeatics</p>

<p>
<strong>Subsidiary Paper </strong>:Two subject from the above list(except the one as an Honours subject) may be chosen as Subsidiary subjects.
</p>
<p>

<strong>Compulsory Paper </strong>: Composition
</p>
<p> a. For Hindi students : Hindi 100 marks  </p>
<p> b. For Non-Hindi students : 50 Marks Hindi & 50 marks Mil (Bangla/Urdu/Oriya/Alt.Eng/Santhali/Ho)</p>
<p>
	<hr>
	<hr>

app/views/tenders/_form.html.erb
<%= form_for(@tender, :html => { :multipart => true}) do |f| %>
  <% if @tender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tender.errors.count, "error") %> prohibited this tender from being saved:</h2>

      <ul>
      <% @tender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">

  <div class="form-group">
    <%= f.label :tender_details %><br>
    <%= f.text_area :tender_details, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tender_publish_date %><br>
    <%= f.date_select :tender_publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tender_due_date %><br>
    <%= f.date_select :tender_due_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :document %><br>
    <%= f.file_field :document, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
</div>
<% end %>

app/views/tenders/edit.html.erb
<h1>Editing Tender</h1>

<%= render 'form' %>

<%= link_to 'Show', @tender %> 
<%= link_to 'Back', tenders_path %>

app/views/tenders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
<h1>Listing Tenders</h1>



<table class="table table-striped">
  <thead>
    <tr>
      <th>Tender Details</th>
      <th>Tender Publish Date</th>
      <th>Tender Due Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</div>

  <tbody>
    <% @tenders.each do |tender| %>
      <tr>
        <td><%= tender.tender_details %></td>
        <td><%= tender.tender_publish_date %></td>
        <td><%= tender.tender_due_date %></td>
        <td><%= link_to 'Show', tender %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tenders/new.html.erb
<h1>New Tender</h1>

<%= render 'form' %>

<%= link_to 'Back', tenders_path %>

app/views/tenders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

<p>
  <strong>Tender details:</strong>
  <%= @tender.tender_details %>
</p>

<p>
  <strong>Tender publish date:</strong>
  <%= @tender.tender_publish_date %>
</p>

<p>
  <strong>Tender due date:</strong>
  <%= @tender.tender_due_date %>
</p>

<p><strong><%= link_to "View Tender Paper", @tender.document.url, target: "_blank" %></strong><p>


<%= link_to 'Back', tenders_path %>
</div>